<?php
$a=$_POST['Name'];
$b=$_POST['Sur_name'];
$c=$_POST['Number1'];
$d=$_POST['Number2'];
$e=$_POST['E_mail_ID'];
$f=$_POST['Site_data'];
$g=$_POST['Price'];
$connect=mysqli_connect("localhost","mysite","","mysitedata");
$query="INSERT INTO `booking`(`Name`, `Sur_name`, `Number1`, `Number2`, `E_mail_ID`, `Site_data`, `Price`) VALUES('$a','$b','$c','$d','$e','$f','$g')";
$Run=mysqli_query($connect,$query);
if ($Run==True)
{
$apikey="rzp_test_IimxSY1LWbybZM";
?>
<form action="https://www.example.com/payment/success/" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apikey;?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_POST['Price']*100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID' .rand(10,100) .'END';?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Acme Corp"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="images/pic1.jpg"
    data-prefill.name="<?php echo $_POST['Price']?>"
    data-prefill.email="anmol@example.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
<?php
}
else
{
echo "not inserted" .mysqli_error($connect);
}
?>